# Using arrays and scalars

In [3]:
import numpy as np

importing numpy library

In [4]:
from __future__ import division

In [5]:
arr1 = np.array([[1,2,3],[8,9,10]])

Create a new two dimensional array of integers arr1

In [6]:
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

print out the array 

In [8]:
#Multiplying Arrays
arr1*arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

Multiply two arrays of integers

In [7]:
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

Subtract arr1 from arr1

In [8]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])

In [9]:
arr1**1

array([[ 1,  2,  3],
       [ 8,  9, 10]], dtype=int32)

Exponential (1)

In [10]:
arr1**3

array([[   1,    8,   27],
       [ 512,  729, 1000]], dtype=int32)

Exponential (3)